---
version: '3.7'
services:
  freqtrade:
    image: terrarebirth/freqtrade.ai:stable
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: 1
    build:
      dockerfile: "./docker/Dockerfile.freqai"
    restart: unless-stopped
    secrets:                    # secrets block only for 'freqtrqde' service
     - FREQTRADE__EXCHANGE__KEY
     - FREQTRADE__EXCHANGE__SECRETE
    container_name: freqtrade_ai
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.ai.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.ai.sqlite
      --config /freqtrade/user_data/config.ai.json
      --strategy FreqaiExampleStrategy
      --freqaimodel LightGBMRegressor
      --strategy-path freqtrade/templates
secrets:                       # top level secrets block
  FREQTRADE__EXCHANGE__SECRET:
    external: true
  FREQTRADE__EXCHANGE__KEY:
    external: true
