---
version: '3'
services:
  freqtrade:
    image: terrarebirth/freqtrade.ai:stable
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              driver: nvidia
              count: 1
    build:
      dockerfile: "./docker/Dockerfile.freqai"
    restart: unless-stopped
    container_name: freqtrade_aihybird
    volumes:
      - "./user_data:/freqtrade/user_data"
    ports:
      - "8080:8080"
    command: >
      trade
      --logfile /freqtrade/user_data/logs/freqtrade.aihybird.log
      --db-url sqlite:////freqtrade/user_data/tradesv3.aihybird.sqlite
      --config /freqtrade/user_data/config.aihybird.json
      --strategy FreqaiExampleHybirdStrategy
      --freqaimodel LightGBMRegressor
      --strategy-path freqtrade/templates
