ARG sourceimage=terrarebirth/freqtrade.dev
ARG sourcetag=stable
FROM ${sourceimage}:${sourcetag}

# Install dependencies
COPY requirements-freqai.txt /freqtrade/

RUN pip install -r requirements-freqai.txt --user --no-cache-dir
